### ISSUE TITLE
Mises

### ISSUE THREAD

**Issue by Shadamm** [sxlmnwb/mainnet_manuals#1]

**Comment by sxlmnwb** [comment]
what ?

**Comment by Shadamm** [comment]
Knapa bang

Pada tanggal Sel, 29 Nov 2022 20.05, Salman Wahib ***@***.***>
menulis:

**Comment by sxlmnwb** [comment]
Napa lu open pull request ada kode yang error tah ?

**Comment by Shadamm** [comment]
Gua gangerti bang garapnya
Baru join grup bg.pateng

Pada tanggal Sel, 29 Nov 2022 20.09, Salman Wahib ***@***.***>
menulis:
